# Generated by Django 6.0.3 on 2026-03-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Appointment', 'Appointment')], default='Consultation', max_length=20),
        ),
    ]
